#! /usr/bin/env python

import os
import subprocess
import sys

import yaml

ABS_PATH = os.path.dirname(__file__)


def load_config(config_file):
    with open(ABS_PATH + '/' + config_file, "r") as file:
        config = yaml.safe_load(file)
    return config


def run_command(command, args, config):
    if command in config["commands"].keys():
        if args[0] in config["commands"][command].keys():
            command_to_execute = config["commands"][command][args[0]] + ' ' + ' '.join(args[1:])
            print("Executing:", command_to_execute)
            subprocess.run(command_to_execute, shell=True)
        else:
            command_to_execute = command + ' ' + ' '.join(args)
            print("Executing:", command_to_execute)
            subprocess.run(command_to_execute, shell=True)
    else:
        print(f"Unknown command: {command[0]}")


# def find_command(input, config):




if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python custom_script.py <config_file> <command>")
        sys.exit(1)

    stack = sys.argv[1:]
    config_file = stack.pop(0)
    command = stack.pop(0)
    args = stack

    config = load_config(config_file)
    run_command(command, args, config)
